### ISSUE TITLE
Претензия к товарному знаку

### ISSUE THREAD

**Issue by PhantornRU** [Lost-Paradise-Project/Lost-Paradise#276]
# Нарушение товарного знака
Выражаем претензию в связи с использованием Вами товарного знака "Lost Paradise", который идентичен зарегистрированному товарному знаку № 1052897, принадлежащему Акционерному обществу "Татспиртпром". 

Согласно данным Роспатента, товарный знак "Lost Paradise" был зарегистрирован 01.10.2024 года за Акционерным обществом "Татспиртпром" и охраняется исключительными правами до 14.11.2033 года. 

Использование Вами названия "Lost Paradise" и присваивания его по лицензии [LICENSE-AGPLv3](https://github.com/Lost-Paradise-Project/Lost-Paradise/blob/master/LICENSE-AGPLv3.txt) @Flybik является прямым нарушением исключительных прав на товарный знак, установленных законодательством РФ. 

Мы настоятельно требуем прекратить использование товарного знака "Lost Paradise".

В противном случае, мы будем вынуждены обратиться в суд для защиты прав и интересов, а также взыскания убытков, понесенных в связи с нарушением исключительных прав на товарный знак. 

### Лицензия
Проверить товарный знак вы можете на сайте:
https://onlinepatent.ru/trademarks/1052897/

### Скриншоты

![image](https://github.com/user-attachments/assets/e7f9d2a6-5de7-4236-91de-72ae8ffd4dfb)

**Comment by Evgencheg** [comment]
> # Нарушение товарного знака
> Выражаем официальную претензию в связи с использованием Вами товарного знака "Lost Paradise", который идентичен зарегистрированному товарному знаку № [1052897](tel:1052897), принадлежащему Акционерному обществу "Татспиртпром".
> 
> Согласно данным Роспатента, товарный знак "Lost Paradise" был зарегистрирован 01.10.2024 года за Акционерным обществом "Татспиртпром" и охраняется исключительными правами до 14.11.2033 года.
> 
> Использование Вами названия "Lost Paradise" и присваивания его по лицензии [LICENSE-AGPLv3](https://github.com/Lost-Paradise-Project/Lost-Paradise/blob/master/LICENSE-AGPLv3.txt) @Flybik является прямым нарушением исключительных прав на товарный знак, установленных законодательством РФ.
> 
> Мы настоятельно требуем прекратить использование товарного знака "Lost Paradise".
> 
> В противном случае, мы будем вынуждены обратиться в суд для защиты своих прав и интересов, а также взыскания убытков, понесенных в связи с нарушением исключительных прав на товарный знак.
> 
> ### Лицензия
> Проверить товарный знак вы можете на сайте: https://onlinepatent.ru/trademarks/1052897/
> 
> ### Скриншоты
> ![image](https://private-user-images.githubusercontent.com/41479614/376603835-e7f9d2a6-5de7-4236-91de-72ae8ffd4dfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTUxNjcsIm5iZiI6MTcyODk5NDg2NywicGF0aCI6Ii80MTQ3OTYxNC8zNzY2MDM4MzUtZTdmOWQyYTYtNWRlNy00MjM2LTkxZGUtNzJhZThmZmQ0ZGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDEyMjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZGE2ZGRhZTc5MDJlM2ZlY2I4Y2FmODdlY2FhNTA5MGI5OTljY2U1NDUyOTVjY2MxMzQzNGIyOTQwZjg3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x5UraUwDzT8p5i_m8SS-qK5QJx1q4DjamvbwgJrQO-w)

Приветствую. Являетесь ли вы владельцем товарного знака или его правомерным представителем? Проект был зарегистрирован достаточно давно, еще до ноября 2023 года что вы можете проверить у нас в дискорде.

**Comment by PhantornRU** [comment]
> Приветствую. Являетесь ли вы владельцем товарного знака или его правомерным представителем? Проект был зарегистрирован достаточно давно, еще до ноября 2023 года что вы можете проверить у нас в дискорде.

### Благодарю за обращение. 

Я не являюсь владельцем товарного знака "Lost Paradise" и не имею полномочий представлять его правообладателя.  

Однако, могу уточнить, что информация о регистрации товарного знака № 1052897 на имя Акционерного общества "Татспиртпром" была размещена на официальном сайте Роспатента 01.10.2024 года. 

Если проект "Lost Paradise" был зарегистрирован до ноября 2023 года, как Вы утверждаете, то он, вероятно, использует название без надлежащей правовой защиты. 

Рекомендую обратиться к правообладателю товарного знака - Акционерному обществу "Татспиртпром" - для уточнения деталей.

**Comment by Evgencheg** [comment]
> > Приветствую. Являетесь ли вы владельцем товарного знака или его правомерным представителем? Проект был зарегистрирован достаточно давно, еще до ноября 2023 года что вы можете проверить у нас в дискорде.
> 
> ### Благодарю за обращение.
> Я не являюсь владельцем товарного знака "Lost Paradise" и не имею полномочий представлять его правообладателя.
> 
> Однако, могу уточнить, что информация о регистрации товарного знака № [1052897](tel:1052897) на имя Акционерного общества "Татспиртпром" была размещена на официальном сайте Роспатента 01.10.2024 года.
> 
> Если проект "Lost Paradise" был зарегистрирован до ноября 2023 года, как Вы утверждаете, то он, вероятно, использует название без надлежащей правовой защиты.
> 
> Рекомендую обратиться к правообладателю товарного знака - Акционерному обществу "Татспиртпром" - для уточнения деталей.

Так вот как получается. Вы не являетесь ни владельцем ни правовым представителем этого товарного знака. Значит вы не можете отправить вашу заявку в суд. Связаться обязательно можем и сделаем в кратчайшие сроки. У меня возник один вопрос, почему вам стало интересно и вы залезли и пошли искать патент на данное название? Почему же мейнтейрер сс220 занимается подобным?

**Comment by Xeno4** [comment]
> Вы правы, я не владелец и не представитель "Lost Paradise" и не могу подать на них в суд.
> 
> Что касается моего интереса к этому вопросу, то:
> 
> * Мы следим за правовой чистотой проектов.
> * Подобные ситуации могут привести к конфликтам. В случае, если проект "Lost Paradise" использует название без прав, могут возникнуть споры, которые могут привести к юридическим проблемам как для них, так и для других проектов, работающих в той же сфере.
> * Проверка - стандартная процедура. Проверка на наличие регистрации товарных знаков - стандартная практика при разработке новых проектов. Это помогает убедиться в отсутствии конфликтов с другими проектами и избежать правовых проблем в будущем.
> 
> Мы ни в коем случае не хотим выступать в роли "охотников за патентами". Наша цель - просто информировать о возможных правовых рисках и предложить помощь в решении подобных ситуаций.
> 
> Надеюсь, это проясняет мои действия. Мы готовы обсудить ситуацию подробнее и помочь вам найти решение, которое устроит всех сторон.

Класс МКТУ товарного знака, который вы скинули - 33. Это означает, что, даже если владелец проекта захочет зарегистрировать товарный знак "Lost Paradise", то ему ничего не помешает, так как это будет другой класс МКТУ

**Comment by PhantornRU** [comment]
Вы правы, класс МКТУ 33 не препятствует регистрации "Lost Paradise" в другом классе. 

Но, стоит помнить, что сходство названий может вызвать путаницу у потребителей и привести к конфликтам с правообладателем. 

Рекомендую проконсультироваться с юристом по интеллектуальной собственности, чтобы получить более точную оценку ситуации. 

Рад был помочь разобраться с этим вопросом!

**Comment by RinKeeper** [comment]
Фурри из 220 с нейронкой решил попрактиковаться в спорах о товарных знаках, но нейронка ему не объяснила что она не является ультимативным инструментом для юридических споров

**Comment by LoneAsket** [comment]
*Жёстко кринжанул с Пупса*

**Comment by Lime-7** [comment]
> _Жёстко кринжанул с Пупса_

люто кринжанул с СС14
![image](https://github.com/user-attachments/assets/851733fe-aff9-45d7-8705-4ec161e5b628)
